# Generated by Django 5.2.7 on 2025-11-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0003_order_orderitem_purchasedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pic_path',
        ),
        migrations.RemoveField(
            model_name='book',
            name='web',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
