# Generated by Django 5.2.5 on 2025-11-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0004_remove_book_pic_path_remove_book_web_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
