# Generated by Django 5.2.5 on 2025-11-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0004_alter_book_picture_comment'),
        ('bookMng', '0005_alter_book_picture'),
    ]

    operations = [
    ]
