# Generated by Django 5.2.5 on 2025-11-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0006_merge_20251103_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
